#!/usr/bin/env python3
"""Emit a filter-chain.conf from a fit-eq.py result.

  ./fit/fit-eq.py target.txt 10 > fit.txt
  ./generate/gen-filter-chain.py fit.txt > filter-chain.conf

Copy the result into Omarchy as
default/audio/tunings/<vendor>-<model>/filter-chain.conf and add a tuning.conf
beside it.

Reads the sections and global gain that fit-eq.py printed, so nothing is
transcribed by hand. The speaker sink is left as @SPEAKER_SINK@; the framework
substitutes the detected sink when the tuning is installed.

Channels are wired explicitly rather than relying on a mono graph being
duplicated per channel, because the limiter is a stereo plugin and a duplicated
mono graph would limit each side independently, shifting the stereo image on bass
transients.
"""

import re
import sys

LABELS = {
    "highpass": "bq_highpass",
    "lowpass": "bq_lowpass",
    "peaking": "bq_peaking",
    "lowshelf": "bq_lowshelf",
    "highshelf": "bq_highshelf",
}

SINK = "omarchy_speaker_tuning"


def parse(path):
    sections, gain = [], 1.0
    for line in open(path):
        m = re.match(r"#\s*global gain:.*\(linear\s+([\d.]+)\)", line)
        if m:
            gain = float(m.group(1))
            continue
        m = re.match(
            r"(\w+)\s+Freq=\s*([\d.]+)\s+Q=([\d.]+)(?:\s+Gain=([-+][\d.]+))?", line)
        if m and m.group(1) in LABELS:
            kind, freq, q, g = m.groups()
            sections.append(
                (LABELS[kind], float(freq), float(q), float(g) if g else None))
    return sections, gain


def main():
    if len(sys.argv) != 2:
        print(__doc__.strip(), file=sys.stderr)
        sys.exit(2)

    sections, gain = parse(sys.argv[1])
    if not sections:
        print("No sections found; is that a fit-eq.py output file?",
              file=sys.stderr)
        sys.exit(1)

    nodes, links = [], []
    for ch in ("l", "r"):
        prev = None
        for i, (label, freq, q, g) in enumerate(sections):
            name = f"s{i}_{ch}"
            ctrl = f'"Freq" = {freq} "Q" = {q}'
            if g is not None:
                ctrl += f' "Gain" = {g}'
            nodes.append(f"          {{ type = builtin name = {name:9s} "
                         f"label = {label:12s} control = {{ {ctrl} }} }}")
            if prev:
                links.append(
                    f'          {{ output = "{prev}:Out" input = "{name}:In" }}')
            prev = name
        links.append(
            f'          {{ output = "{prev}:Out" input = "limiter:in_{ch}" }}')
        nodes.append("")

    newline = chr(10)
    print(f'''# Speaker tuning generated by gen-filter-chain.py.
#
# {len(sections)} biquads per channel followed by a lookahead limiter. Record the
# measurements that justify these values in tuning.conf; see the
# omarchy-audio-tuner README for what a tuning has to report.

context.modules = [
  {{ name = libpipewire-module-filter-chain
    args = {{
      node.description = "Laptop Speakers"
      media.name       = "Laptop Speakers"

      filter.graph = {{
        nodes = [
{newline.join(nodes)}          {{ type   = lv2
            name   = limiter
            plugin = "http://lsp-plug.in/plugins/lv2/limiter_stereo"
            control = {{
              # Both default to enabled: "alr" regulates level toward the
              # threshold and "boost" normalises the threshold up to full
              # scale. A fixed tuning must switch them off or its tone drifts
              # with programme level.
              "alr"   = 0
              "boost" = 0
              # Broadband makeup from the fit, carried by the limiter's input
              # gain so no separate gain stage is needed.
              "g_in"  = {gain}
              "th"    = 0.891
            }}
          }}
        ]

        links = [
{newline.join(links)}
        ]

        inputs  = [ "s0_l:In" "s0_r:In" ]
        outputs = [ "limiter:out_l" "limiter:out_r" ]
      }}

      audio.channels = 2
      audio.position = [ FL FR ]

      capture.props = {{
        node.name   = "{SINK}"
        media.class = Audio/Sink
      }}
      playback.props = {{
        node.name     = "{SINK}_output"
        node.passive  = true
        target.object = "@SPEAKER_SINK@"
      }}
    }}
  }}
]''')


if __name__ == "__main__":
    main()
